// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjlKdux9zZgjn7XqLD5TgEOuc0d6P8KEo',
    appId: '1:1006154589185:web:be98ce72a35811be214c00',
    messagingSenderId: '1006154589185',
    projectId: 'flutter-project-a5fbb',
    authDomain: 'flutter-project-a5fbb.firebaseapp.com',
    storageBucket: 'flutter-project-a5fbb.firebasestorage.app',
    measurementId: 'G-YFGW9G38DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACST8yh26PdHAoaONRpsU6R_xK7ibUzhA',
    appId: '1:1006154589185:android:0dffe3dda12383bd214c00',
    messagingSenderId: '1006154589185',
    projectId: 'flutter-project-a5fbb',
    storageBucket: 'flutter-project-a5fbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhsrtV8sJTvbuRHxNJ-8EHIbglClPYBDU',
    appId: '1:1006154589185:ios:3ef49bb341f11a75214c00',
    messagingSenderId: '1006154589185',
    projectId: 'flutter-project-a5fbb',
    storageBucket: 'flutter-project-a5fbb.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhsrtV8sJTvbuRHxNJ-8EHIbglClPYBDU',
    appId: '1:1006154589185:ios:3ef49bb341f11a75214c00',
    messagingSenderId: '1006154589185',
    projectId: 'flutter-project-a5fbb',
    storageBucket: 'flutter-project-a5fbb.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjlKdux9zZgjn7XqLD5TgEOuc0d6P8KEo',
    appId: '1:1006154589185:web:da15af3ac7b17eb1214c00',
    messagingSenderId: '1006154589185',
    projectId: 'flutter-project-a5fbb',
    authDomain: 'flutter-project-a5fbb.firebaseapp.com',
    storageBucket: 'flutter-project-a5fbb.firebasestorage.app',
    measurementId: 'G-BF10GC3NWS',
  );
}
